Proposed updates to schema
urbanopt/geojson-modelica-translator pull request #172
Opened 2020-08-20 03:58 UTC by amyeallen1

Hi Nick and Hagar, this PR has the proposed changes to the schema that we discussed last week. The list of ETS properties could be extended in the future as we support more ETS types. The "ets_name" property is a placeholder to allow one to set different values of properties for heating vs. cooling. @Helarga @nllong

2020-08-31 14:48 UTC, amyeallen1 commented
Hi Hagar and Nick, 
Hagar, thanks for reviewing this. I made the changes you suggested (making the units mass flow rate as opposed to volumetric flow rate) and removed some duplicate content. @Helarga @nllong

2020-09-15 18:48 UTC, nllong requested changes
This is great, thanks for updating the schema. I have a few requested changes. 

Make sure to run `py.test` locally to ensure all the tests pass.

2020-09-15 18:48 UTC, nllong commented on geojson_modelica_translator/system_parameters/schema.json
> +        "ets": {
with this setup it appers that all buildings will get the same ETS system, is that what is expected?

2020-09-15 18:48 UTC, nllong commented on geojson_modelica_translator/system_parameters/schema.json
> +                "1G Indirect",
I'm not sure I like the 1G, 2/3 G style naming. Any other thoughts on making this look better? Maybe break up generation as (First Generation, Second Generation), and ETS connection type (Direct, Indirect)?

2020-09-15 18:48 UTC, nllong commented on geojson_modelica_translator/system_parameters/schema.json
> +            "ets_type_cooling": {
I renamed this to ets_type_cooling instead of ets_type_clg.

2020-09-15 18:48 UTC, nllong commented on tests/system_parameters/data/system_params_1.json
> +  "ets": {
Can you update the various system_params JSON files in the repo to the new schema format? This is in part why the tests are failing.

2020-09-24 01:46 UTC, amyeallen1 commented on geojson_modelica_translator/system_parameters/schema.json
> +        "ets": {
Good point! I revised the structure of the schema so that one can set defaults overall, and then customize at the building level.

2020-09-24 01:46 UTC, amyeallen1 commented on geojson_modelica_translator/system_parameters/schema.json
> +                "1G Indirect",
That makes sense. I revised the naming, and added another property so that the generation and connection type are separate properties.

2020-09-24 01:47 UTC, amyeallen1 commented on tests/system_parameters/data/system_params_1.json
> +  "ets": {
Good point. I updated the test files.

2020-09-29 02:56 UTC, nllong approved these changes

2020-09-29 03:35 UTC, nllong approved these changes

2020-09-29 03:36 UTC, merged

2020-09-29 03:38 UTC, amyeallen1 commented
Thanks, Nick!

On Mon, Sep 28, 2020 at 9:36 PM Nicholas Long <notifications@github.com>
wrote:

> Merged #172
> <https://github.com/urbanopt/geojson-modelica-translator/pull/172> into
> develop.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbanopt/geojson-modelica-translator/pull/172#event-3817299789>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFRGGVKNBKAAZDZAOD5YEK3SIFI33ANCNFSM4QFTQHBQ>
> .
>