Heating indirect template
urbanopt/geojson-modelica-translator pull request #182
Opened 2020-09-16 20:25 UTC by vtnate

#### Any background context you want to provide?
Bringing in HeatingIndirect.mot
#### What does this PR accomplish?
Allows use of indirect heating template in district system
#### How should this be manually tested?
@nllong Is there a template I can use to write tests for this? I don't see one anywhere for CoolingIndirect.mot. I poked at testing DistrictHeatingSystem.mot, but that seems like a different thing and I haven't gotten that template working yet.
#### What are the relevant tickets? #178

2020-09-16 21:54 UTC, nllong requested changes
small changes requested. Yes this looks good. 

The way to test this is to create a new test file. I'd copy this one (https://github.com/urbanopt/geojson-modelica-translator/blob/develop/tests/model_connectors/test_district_system.py) and call it test_district_heating.py or something like that. Then you will need to update the system parameter file to use indirect with heating.

2020-09-16 21:54 UTC, nllong commented on geojson_modelica_translator/model_connectors/templates/DistrictHeatingSystem.mot
> +    within Buildings.Applications.DHC.CentralPlants.Heating.Generation4.Examples;model DistrictHeatingSystem3BuiNewBoiler
This should be `within geojson_modelica_translator.model_connectors.templates;`

2020-09-16 21:54 UTC, nllong commented on geojson_modelica_translator/model_connectors/templates/DistrictHeatingSystem.mot
> +    within Buildings.Applications.DHC.CentralPlants.Heating.Generation4.Examples;model DistrictHeatingSystem3BuiNewBoiler
Also, can you make sure to run the modelica-fmt. You just need to install modelica-fmt, then the pre-commit will use it. Grab latest release from the assets here: https://github.com/urbanopt/modelica-fmt/releases/tag/v0.1-pr.3. Make sure to place it in your path.

2020-09-16 21:54 UTC, nllong commented on geojson_modelica_translator/model_connectors/district_system.py
> +            if "Heating" in ets_model_type:
nice... 

Yeah, I think we can remove the model_name object here unless the HeatingINdirect.mot is looking for a model_name.

2020-09-16 21:54 UTC, nllong commented on geojson_modelica_translator/system_parameters/schema.json
> +    "ets_indirect_parameters": {
thanks for updating the schema. Note that this is going to conflict with Amy's PR (https://github.com/urbanopt/geojson-modelica-translator/pull/172) and with https://github.com/urbanopt/geojson-modelica-translator/pull/180. But I guess the first in wins.

2020-09-16 21:54 UTC, nllong commented on tests/geojson_modelica_translator/data/system_parameters_mix_models.json
> +          "heating_supply_water_temperature_building": 50
yeah, i like this pattern.

2020-09-16 21:54 UTC, nllong commented on tests/model_connectors/test_district_system.py
> +    # def test_district_heating_to_modelica_and_run(self):
just delete this code.

2020-09-17 23:11 UTC, vtnate commented
> small changes requested. Yes this looks good.
> 
> The way to test this is to create a new test file. I'd copy this one (https://github.com/urbanopt/geojson-modelica-translator/blob/develop/tests/model_connectors/test_district_system.py) and call it test_district_heating.py or something like that. Then you will need to update the system parameter file to use indirect with heating.

@nllong It looks like we don't have anything that explicitly tests `CoolingIndirect.mot` and it just gets used during operation of `DistrictCoolingSystem.mot`, is that correct? So therefore the same goes for `HeatingIndirect.mot`?

Something still isn't right with the template, so @Helarga and I are going over it tomorrow morning.

2020-09-24 20:04 UTC, vtnate commented
Ugh. @nllong Travis wants modelica-fmt to make changes, but it passed locally before I pushed. Also, Travis canceled the CI build because the district cooling test took longer than 10 minutes. That test takes 17 minutes on my laptop. Can you confirm locally that the tests pass, and maybe adjust the Travis settings?

2020-09-25 14:51 UTC, nllong commented
1) Make sure to install modelica fmt 0.1-pr3 (https://github.com/urbanopt/modelica-fmt/releases/tag/v0.1-pr.3). I ran locally and it did make the changes.
2) Yes, the >10 minute is an issue because when running in jmodelica then isn't any data being written out, therefore, travis kills the process. We can either a) figure out how to make the simulation run in < 10 minutes, or b) find a way to echo something to stdout while waiting on jmodelica.  I vote for b.

2020-09-25 15:22 UTC, Helarga commented
> 1. Make sure to install modelica fmt 0.1-pr3 (https://github.com/urbanopt/modelica-fmt/releases/tag/v0.1-pr.3). I ran locally and it did make the changes.
> 2. Yes, the >10 minute is an issue because when running in jmodelica then isn't any data being written out, therefore, travis kills the process. We can either a) figure out how to make the simulation run in < 10 minutes, or b) find a way to echo something to stdout while waiting on jmodelica.  I vote for b.
@nllong for the cooling district plant we have used 8 spawn buildings, i will replace it with 2 as the Heating District Plant

2020-09-25 15:23 UTC, nllong commented
> > 1. Make sure to install modelica fmt 0.1-pr3 (https://github.com/urbanopt/modelica-fmt/releases/tag/v0.1-pr.3). I ran locally and it did make the changes.
> > 2. Yes, the >10 minute is an issue because when running in jmodelica then isn't any data being written out, therefore, travis kills the process. We can either a) figure out how to make the simulation run in < 10 minutes, or b) find a way to echo something to stdout while waiting on jmodelica.  I vote for b.
> >    @nllong for the cooling district plant we have used 8 spawn buildings, i will replace it with 2 as the Heating District Plant

that will help, thanks @Helarga !

2020-09-25 16:59 UTC, Helarga commented
@vtnate  Hi Nate, so locally the simulation on Jmodelica took 29.8 seconds
![image](https://user-images.githubusercontent.com/47648835/94295169-1256c680-ff1e-11ea-9d61-06fcdb60d175.png)

2020-09-25 18:58 UTC, vtnate commented
Thanks Hagar!

And sorry Nick, I wasn't clear in my comment. I have modelica-fmt 0.1-pr3 which ran and updated the modelica files locally before I pushed. That's why I was surprised it it failed CI.

2020-09-25 19:10 UTC, vtnate commented
Ugh: https://travis-ci.org/github/urbanopt/geojson-modelica-translator/jobs/730353040 modelica-fmt again. All the py.tests passed though!

2020-09-25 19:28 UTC, vtnate commented
Welp, I learned my lesson. Need to run all files through pre-commit, not just let the hook run when you make a commit. Hopefully this note can help others avoid this frustration.

2020-09-25 23:39 UTC, nllong commented
Ah, right, I should have said this more clearly too. By default pre-commit only runs on files that have changed in the staged commit. If you haven't been keeping up to date, then you need to run `pre-commit run --all-files`

2020-09-28 15:59 UTC, nllong approved these changes
amazing, thanks everyone!

2020-09-28 16:00 UTC, merged