Enhancement/modelica csv
urbanopt/geojson-modelica-translator pull request #227
Opened 2020-11-18 04:31 UTC by vtnate

#### Any background context you want to provide?
This updates the CSVModelica class, to transform OpenStudio output into Modelica (Dymola) input
#### What does this PR accomplish?
Reads current output from [this measure](https://github.com/urbanopt/DES_HVAC/tree/develop/Measures/export_time_series_modelica) and turns it into a Dymola input file
#### How should this be manually tested?
Call the class on a file created by that measure.
- The existing test no longer works, due to new column names. We need to create a new test input file.
- The measure now takes care of presenting seconds since the year started
#### What are the relevant tickets? #224 
#### Screenshots (if appropriate)

2020-11-18 04:33 UTC, vtnate commented
@Helarga If we use a new input data file created from Amy's measure, this should be tickety boo. I'll need to update the test file to deal with it. Checking with you before I get too wild and crazy.

2020-11-18 19:26 UTC, vtnate commented
@nllong I'm confused. The test suite includes a test that reads the output file, which passes, but I don't see the output file getting created in the `output` directory as expected. Can you help me find my bug?

2020-11-18 19:27 UTC, vtnate commented
Also, pre-commit touched other files. This PR is intended to only impact `csv_modelica.py` and `test_csv_modelica.py`

2020-11-20 15:29 UTC, nllong requested changes
One question about documentation. Otherwise, looks good.

2020-11-20 15:29 UTC, nllong commented on tests/modelica/test_csv_modelica.py
> +            input_file = Path(self.data_dir) / 'DNE.csv'
haha, i like how you update these when you find them ;p

2020-11-20 15:29 UTC, nllong commented on geojson_modelica_translator/modelica/csv_modelica.py
> -        3: TChWR, double, Temperature chilled water return, degC
I feel like we should keep this documentation?

2020-11-20 15:30 UTC, nllong commented
> @nllong I'm confused. The test suite includes a test that reads the output file, which passes, but I don't see the output file getting created in the `output` directory as expected. Can you help me find my bug?

Yep, I'll look today.

2020-11-20 15:49 UTC, nllong commented
> > @nllong I'm confused. The test suite includes a test that reads the output file, which passes, but I don't see the output file getting created in the `output` directory as expected. Can you help me find my bug?
> 
> Yep, I'll look today.

File gets created here: 
```
(3.7.7-gmt) ➜  geojson-modelica-translator git:(enhancement/modelica-csv) head tests/modelica/output/modelica.csv
#1
double /Users/nlong/working/urban-analysis/geojson-modelica-translator/tests/modelica/output/modelica.csv(8760, 7)
#Nominal heating water mass flow rate=43.24
#Nominal chilled water mass flow rate=117.64
#time,heatingReturnTemperature[C],heatingSupplyTemperature[C],massFlowRateHeating,ChilledWaterReturnTemperature[C],ChilledWaterSupplyTemperature[C],massFlowRateCooling
0,58.5,82.22,7.45,15.48,6.68,16.98
3600,82.22,82.22,0.0,6.68,6.68,0.0
7200,57.1,82.22,8.95,15.38,6.68,18.57
10800,82.22,82.22,0.0,6.68,6.68,0.0
14400,52.74,82.22,4.06,15.41,6.68,10.35
```

2020-11-24 16:19 UTC, vtnate commented on tests/modelica/test_csv_modelica.py
> +            input_file = Path(self.data_dir) / 'DNE.csv'
We've all gotta have our neuroses, right? 😁

2020-11-24 16:21 UTC, vtnate commented on geojson_modelica_translator/modelica/csv_modelica.py
> -        3: TChWR, double, Temperature chilled water return, degC
Happy to keep it. I'll add some clarifying text, because none of this is applicable to [Amy's measure](https://github.com/urbanopt/DES_HVAC/tree/develop/Measures/export_time_series_modelica), which is all we are supporting with this PR.

2020-11-24 16:25 UTC, vtnate commented
> > > @nllong I'm confused. The test suite includes a test that reads the output file, which passes, but I don't see the output file getting created in the `output` directory as expected. Can you help me find my bug?
> > 
> > 
> > Yep, I'll look today.
> 
> File gets created here:
> 
> ```
> (3.7.7-gmt) ➜  geojson-modelica-translator git:(enhancement/modelica-csv) head tests/modelica/output/modelica.csv

Fascinating. That file isn't showing up in my file list, despite the test passing.

2020-11-24 17:41 UTC, nllong commented
> tests/modelica/output

check to make sure you are looking in `tests/modelica/output` and not `tests/modelica_connectors/output`

2020-11-24 17:42 UTC, nllong commented on geojson_modelica_translator/modelica/csv_modelica.py
> -        3: TChWR, double, Temperature chilled water return, degC
Yeah, can you keep it? It is nice to know the structure of the files.

2020-11-24 18:49 UTC, vtnate commented
> check to make sure you are looking in `tests/modelica/output` and not `tests/modelica_connectors/output`

I don't wanna credit pathlib for it showing up for me again, but I can see the test output file now, at least. 🤷 😁 
@nllong is that docstring too crazy now, or is that what you're looking for?

2020-11-25 00:37 UTC, nllong approved these changes
yep, this looks good now, thanks!

2020-11-25 00:37 UTC, merged