Move to sys params
urbanopt/geojson-modelica-translator pull request #273
Opened 2020-12-31 17:20 UTC by vtnate

#### Any background context you want to provide?
#### What does this PR accomplish?
- Moves creating a sys_param file from uo_sdk output into the SystemParameters class
#### How should this be manually tested?
Automatic testing:
- `py.test tests/system_parameters/test_system_parameters.py`

Using the CLI for realzies
- `uo_des sys-param -p zzz.json -s tests/system_parameters/data/sdk_output_skeleton/run/baseline_15min -f tests/system_parameters/data/sdk_output_skeleton/example_project.json`
#### What are the relevant tickets?
Resolves #271 Resolves #272  
#### Screenshots (if appropriate)

2021-01-04 16:36 UTC, macintoshpie reviewed
Awesome ⚡ Just a few comments/suggestions

I tested the cli locally using the PR's suggested command and the output looks good to me.

2021-01-04 16:36 UTC, macintoshpie commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +            raise Exception("No template found. You must pass the sys_param_template location when initializing an instance.")
I'm not sure what we could do instead, but I feel like it might be a bit confusing for a user if we mention `sys_param_template` here when it's not mentioned elsewhere in this class

2021-01-04 16:36 UTC, macintoshpie commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +        self.measure_list = []
It might be cleaner to just use a local variable here instead of assigning to self now that we're no longer calling other methods to append to it.

2021-01-04 16:36 UTC, macintoshpie commented on management/uo_des.py
> +    sys_param_template_path = Path(__file__).parent.parent / 'geojson_modelica_translator' / \
Is this template file always going to be the same (ie we don't allow changing the template)?

If so, I wonder if we should just load this inside of the `csv_to_sys_param` method. That would prevent users from initializing the SystemParameters with a json file that's not what we expect when templating. We could also make `csv_to_sys_param` a class method so the caller doesn't have to instantiate the class themselves (see the `loadd` method).

2021-01-04 16:36 UTC, macintoshpie commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +        with open(sys_param_filename, 'w') as outfile:
maybe we could call `validate` before we save the file to make sure it's valid? Though I'm not sure if it's possible or likely that we construct an invalid sys params

2021-01-04 17:32 UTC, nllong commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +    def csv_to_sys_param(self, scenario_dir: Path, feature_file: Path, sys_param_filename: Path, overwrite=True) -> None:
👍

2021-01-04 17:35 UTC, nllong commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +            raise Exception("No template found. You must pass the sys_param_template location when initializing an instance.")
Can we make `self.data` be more explicit (e.g., `self.param_template_data`)?

2021-01-04 17:37 UTC, nllong commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +                if feature['properties']['type'] != 'Site Origin':
ideally this would use `jsonpath_ng` to find the fields.

2021-01-04 17:39 UTC, nllong commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +                feature_name, measure_load_name = str(measure_file_path).split('/')[-3:-1]
can you document the `-3:-1` portion of this line...

2021-01-04 17:45 UTC, nllong commented on management/uo_des.py
> +    sys_param_template_path = Path(__file__).parent.parent / 'geojson_modelica_translator' / \
The template should be configurable outside of the SystemParameters class since the template can change if dealing with time series vs spawn vs others. However, I do think that Ted's point is salient--how does the user know what template to use?

2021-01-04 17:45 UTC, nllong requested changes
Looking good! Few comments that should be addressed.

2021-01-04 23:48 UTC, vtnate commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +            raise Exception("No template found. You must pass the sys_param_template location when initializing an instance.")
I'm working on loading the template in a different manner that won't re-use `self.data` to address this.

2021-01-07 18:54 UTC, vtnate commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +                if feature['properties']['type'] != 'Site Origin':
Abandoned this avenue. jsonpath_ng didn't work, for unknown reasons.

2021-01-07 19:09 UTC, vtnate commented
@nllong @macintoshpie I've updated this PR, can you review again?

2021-01-08 22:49 UTC, macintoshpie commented on management/uo_des.py
> +        sys_param_template=model,
```suggestion
        model_type=model,
```

2021-01-08 22:49 UTC, macintoshpie commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +                    building['load_model_parameters']['time_series']['nominal_flow_building'] = float(building_nominal_mfrt)
This doesn't appear to be in our current schema, should we add it?
Maybe we could add a test as well that runs the json schema validator on the generated result

2021-01-08 23:24 UTC, vtnate commented on management/uo_des.py
> +        sys_param_template=model,
Damn. You're right, of course.

2021-01-08 23:25 UTC, vtnate commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +                    building['load_model_parameters']['time_series']['nominal_flow_building'] = float(building_nominal_mfrt)
ermuhgerd, yes, definitely.

2021-01-10 16:33 UTC, nllong approved these changes
changes look great!

One question that probably needs resolved.

2021-01-10 16:33 UTC, nllong commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +                    building['load_model_parameters']['time_series']['nominal_flow_building'] = float(building_nominal_mfrt)
has this been added?

2021-01-11 15:11 UTC, vtnate commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +                    building['load_model_parameters']['time_series']['nominal_flow_building'] = float(building_nominal_mfrt)
> has this been added?

Not yet. Working on it now.

2021-01-11 19:53 UTC, vtnate commented on geojson_modelica_translator/system_parameters/system_parameters.py
> +                    building['load_model_parameters']['time_series']['nominal_flow_building'] = float(building_nominal_mfrt)
This was resolved in the recent schema changes, I just needed to change a variable name slightly.

2021-01-11 19:57 UTC, vtnate commented
a44406c rearranges the sys-param file, bringing the ets parameters inside the custom building block.

2021-01-12 16:46 UTC, nllong approved these changes
Thanks for updating the location of the ETS data.

2021-01-12 16:46 UTC, nllong commented on geojson_modelica_translator/system_parameters/time_series_template.json
> +        "ets_model_parameters": {
this looks good!

2021-01-12 16:47 UTC, nllong commented
Hey @vtnate -- I think this is ready to merge. To make sure, we will address cleaning up the other sys param files in #284 as a separate PR?

2021-01-12 16:51 UTC, vtnate commented
> Hey @vtnate -- I think this is ready to merge. To make sure, we will address cleaning up the other sys param files in #284 as a separate PR?

Yes. #284 is low-risk, except for the one concern I raised in that PR.

2021-01-12 16:51 UTC, nllong commented
> > Hey @vtnate -- I think this is ready to merge. To make sure, we will address cleaning up the other sys param files in #284 as a separate PR?
> 
> Yes. #284 is low-risk, except for the one concern I raised in that PR.

cool cool. merging! w00t w00t. 🤘

2021-01-12 16:52 UTC, merged