Chp example
urbanopt/geojson-modelica-translator pull request #378
Opened 2021-04-23 16:26 UTC by vtnate

#### Any background context you want to provide?
Mingzhe wrote a CHP modelica file. I'm templatizing it.
#### What does this PR accomplish?
Make a template from the existing CHP model, and fit it into our workflow
#### How should this be manually tested?
#### What are the relevant tickets?
#### Screenshots (if appropriate)

2021-05-05 16:49 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
> +          "type": "string",
If this is type `boolean` it seems to come through with a capital first letter: `True` instead of `true` which makes Modelica sad. Is there a better way to force lowercase than using `string` type?

2021-05-10 13:45 UTC, nllong requested changes
Looks good. I don't think you meant to commit the whole `district_heating_and_cooling_systems` folder into the repo, amiright?

Otherwise, this looks great. Nice and clean!

2021-05-10 13:45 UTC, nllong commented on tests/model_connectors/test_chp_system.py
> +        heating_plant = DistrictCHP(self.sys_params, template_name="DistrictCHP")
excellent!

2021-05-10 13:45 UTC, nllong commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "CHP plant prioritizes electricity over heat",
so True means that it is thermal following or electrical following? Perhaps make the description "True if CHP is thermal_following (prioritized thermal heat over electricity)"

2021-05-10 13:45 UTC, nllong commented on geojson_modelica_translator/model_connectors/plants/heating_plant.py
> +        self.required_mo_files.append(Path(self.template_dir) / 'CentralHeatingPlant.mo')
haha, these will eventually all be replaced!

2021-05-10 13:45 UTC, nllong commented on district_heating_and_cooling_systems/package.order
> +
I don't think that the `district_heating_and_cooling_systems` folder is supposed to be committed into the repo, right?

2021-05-10 14:37 UTC, nllong commented
Looks like this fails in Dymola for this reason. I'm not sure what this means yet.

![image](https://user-images.githubusercontent.com/1907354/117676670-fe896900-b16a-11eb-89bd-90251a4ec3b2.png)

2021-05-10 14:50 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "CHP plant prioritizes electricity over heat",
I'll update that description. You got it right, True means thermal following.

2021-05-10 14:55 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "CHP plant prioritizes electricity over heat",
@mingzhe37 Can you clarify this variable for me? I'm not sure which way is up. :)

2021-05-10 16:07 UTC, mingzhe37 commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "CHP plant prioritizes electricity over heat",
@vtnate In this CHP model the "thermal_following" means thermal has priority over electricity. "thermal_following = True" will active this mode and allow us to give the water outlet setpoint temperature, which is the input signal of "thermal_following" mode.

2021-05-10 16:21 UTC, mingzhe37 commented
> @mingzhe37 Can you help out with the Dymola questions @nllong raised? What does `failed to differentiate the equation` mean in that error message? 

@vtnate @nllong I have not encountered this problem in my environment, below is the simulation result. Could you please tell me your Modelica standard library/Buildings library version and translation setting? 
![dymola_result](https://user-images.githubusercontent.com/46808578/117690548-33e88380-b178-11eb-88f0-abc9518c4217.png)

> @mingzhe37 And how do we handle having a CHP and a central heating plant in the same system? Does `eleFol` just connect to the same port as the district heating plant?

Yes, they should be connected to the same port as the heating plant, due to the same function.

P.S.
@vtnate As we discussed last week, I prepared a CHP model similar to the current "district heating plant", in which necessary components are packaged into one Modelica model to avoid the flat model issue you mentioned in our last meeting. I can use it to generate an example if necessary.
![CHP_plant](https://user-images.githubusercontent.com/46808578/117691550-41ead400-b179-11eb-8e8a-eefeb244e0d8.png)

2021-05-10 19:10 UTC, vtnate commented
> @vtnate @nllong I have not encountered this problem in my environment, below is the simulation result. Could you please tell me your Modelica standard library/Buildings library version and translation setting?

I'm using `issue2204_gmt_mbl` branch of the Buildings library. I get a very similar error

>   Cannot differentiate call to function without derivative or smooth order annotation 'chp_and_central_heating.Districts.DistrictEnergySystem.TimeSerLoa_e4fb9c8d.loa.getDerTableValue(TimeSerLoa_e4fb9c8d.loa.tableID, 1, TimeSerLoa_e0812594.loa.timeScaled, TimeSerLoa_e4fb9c8d.loa.nextTimeEventScaled, pre(TimeSerLoa_e4fb9c8d.loa.nextTimeEventScaled), TimeSerLoa_e4fb9c8d.loa.tableOnFileRead, der(TimeSerLoa_e0812594.loa.timeScaled))' in equation:

in the stdout.log file when running the test file.

2021-05-15 20:24 UTC, mingzhe37 commented
Hi @vtnate @macintoshpie I tested the chp model by running "py.test tests/model_connectors/test_chp_system.py", the GMT test failed in my end as well. However if I run this model in Dymola the test completed successfully, so I guess "FMUException: Failed to estimate the directional derivative at time 130.374." might be a JModelica problem as I found this in PyFMI document. I will keep following this issue.
Besides, I think the way your integrating the CHP inside the heating plant is excellent, it might make the model better if a pump and some signal could be added into the heating plant. I generated the and you can find the revised model at "heat_with_chp/Plants/CentralHeatingPlant.mo". 
I'm not sure if this revision could solve that problem immediately and I would test this in JModelica, but it could make the heating plant model more reasonable, please let me know your thought on this, thank you!

2021-06-15 19:32 UTC, vtnate commented
The model gets built here in the GMT successfully. I've commented out the lines in the test file that run the test 😬  in JModelica, because JModelica can't run the model. The following screenshots show the model ran successfully in Dymola.

Heat flow through one of the buildings:
![Screen Shot 2021-06-15 at 1 26 24 PM](https://user-images.githubusercontent.com/19916206/122111958-8bb08500-cddd-11eb-8ab1-3bde2133c2da.png)
Mass flow through the CHP plant:
![Screen Shot 2021-06-15 at 1 27 31 PM](https://user-images.githubusercontent.com/19916206/122111965-8fdca280-cddd-11eb-8a86-bb114d4a5c5c.png)

2021-06-17 01:39 UTC, nllong commented on geojson_modelica_translator/geojson_modelica_translator.py
> +    heating_plant = HeatingPlantWithOptionalCHP(sys_params)
I like the new name, very clear what it is.

2021-06-17 01:42 UTC, nllong approved these changes
looks great! One small question regarding naming, otherwise, merge away!

2021-06-17 01:42 UTC, nllong commented on geojson_modelica_translator/model_connectors/plants/chp.py
> +        if not self.chp_exists:
noice

2021-06-17 01:42 UTC, nllong commented on tests/model_connectors/data/time_series_system_params_chp.json
> +        "chp_installed": true,
very cool

2021-06-17 01:42 UTC, nllong commented on tests/model_connectors/test_chp_system.py
> +        # self.run_and_assert_in_docker(Path(root_path) / 'DistrictEnergySystem.mo',
🙈

2021-06-17 01:42 UTC, nllong commented on geojson_modelica_translator/model_connectors/plants/chp.py
> +        self.id = 'chpPla_' + simple_uuid()
How about setting the name `chpPla` if it has CHP and `heaPla` if no chp? Thoughts?

2021-06-17 15:06 UTC, vtnate commented on geojson_modelica_translator/model_connectors/plants/chp.py
> +        self.id = 'chpPla_' + simple_uuid()
Done

2021-06-17 15:58 UTC, merged

2021-06-17 15:59 UTC, nllong commented on geojson_modelica_translator/model_connectors/plants/chp.py
> +        self.id = 'chpPla_' + simple_uuid()
very nice, thanks for the update here!