Modification to spawn templating approach to set zone nominal loads programmatically
urbanopt/geojson-modelica-translator pull request #421
Opened 2021-09-11 07:02 UTC by amyeallen1

This PR addresses issue 400 ([https://github.com/urbanopt/geojson-modelica-translator/issues/400](url), by modifying the system design parameters schema to contain arrays of zone nominal heating and cooling loads for a Spawn model, which are used to set the nominal load values in the template. The test input files have also been updated accordingly. 

This approach assumes that nominal loads will be provided in the same order in which the zone names are listed. 

Nick or Ted, does one of you want to review this? Thanks!

2021-09-13 17:01 UTC, macintoshpie requested changes
I can't comment too much on the modelica/modeling correctness, but I left some feedback for python things. Thanks!

2021-09-13 17:01 UTC, macintoshpie commented on geojson_modelica_translator/system_parameters/schema.json
> +        "zone_nom_htg_loads": {
Should we add these new parameters to the "required" list below? e.g. what happens if users don't provide this?
Another option is to create a default somehow.

2021-09-13 23:39 UTC, amyeallen1 commented on geojson_modelica_translator/model_connectors/load_connectors/spawn.py
> +            "zone_nom_htg_loads": str(repr(zone_nom_htg_loads)).replace("[", "{").replace("]", "}").split("rray(", 1)[-1],
Good point--I added a comment.

2021-09-13 23:39 UTC, amyeallen1 commented on geojson_modelica_translator/model_connectors/load_connectors/teaser.py
> +        print(building_template_data['nominal_heat_flow'])
Done!

2021-09-13 23:40 UTC, amyeallen1 commented on geojson_modelica_translator/system_parameters/schema.json
> +            "type": "integer"
Good point--I changed them both to "number."

2021-09-13 23:40 UTC, amyeallen1 commented on geojson_modelica_translator/system_parameters/schema.json
> +        "zone_nom_htg_loads": {
Good point--I added them both to the "required" list.

2021-09-14 01:12 UTC, amyeallen1 commented
Thanks, Ted, for reviewing, and for the useful comments! I made your suggested revisions. 

On further thought, I also realized that it would be better to maintain the use of the scaling factor in the Spawn template as it was before, so I restored that, and changed the test input values accordingly. This screenshot verifies the expected outcome in Modelica (for the mixed loads test as an example), that is, that the nominal load values in each zone are equal to the input values divided by the scaling factor (which has a value of 5) 

![image](https://user-images.githubusercontent.com/23225173/133170951-9f7b5a91-9f18-4eb6-8288-8622b0810231.png)

2021-09-16 15:31 UTC, macintoshpie approved these changes
Looks good from the python side of things! @nllong leaning on you for modelica/modeling review

2021-09-16 15:37 UTC, amyeallen1 commented
Thanks, Ted! @macintoshpie @nllong Nick, I think this is pretty straight forward from the Modelica perspective--the screen shot in the comment above shows the nominal loads set as expected for the test scenario.

2021-09-16 16:09 UTC, nllong approved these changes
baller! only future recommendation would be to name as `zone_nominal_heating_loads` since there is no reason to abbreviate everything.

2021-09-16 16:12 UTC, merged

2021-09-16 16:23 UTC, amyeallen1 commented
Thanks, Nick! Roger that! @nllong