bump dependency versions
urbanopt/geojson-modelica-translator pull request #477
Opened 2022-06-07 21:22 UTC by nllong

Bump locked versions

2022-06-07 22:25 UTC, vtnate requested changes
Besides my 2 small questions, LGTM.

2022-06-07 22:25 UTC, vtnate commented on pyproject.toml
> +#flake8 = ">=4.0.1"
Is this supposed to be commented?

2022-06-07 22:25 UTC, vtnate commented on pyproject.toml
> +sphinx = "5.0.1"
Has this changed to esbonio?

2022-06-08 14:17 UTC, nllong commented on pyproject.toml
> +#flake8 = ">=4.0.1"
yeah, i just removed it. We use the flake8 that is in pre-commit now.

2022-06-08 14:18 UTC, nllong commented on pyproject.toml
> +sphinx = "5.0.1"
I don't think so. Esbonio looks like a language server for sphinx? https://pypi.org/project/esbonio/.. says early development too.

2022-06-08 15:18 UTC, vtnate approved these changes

2022-06-08 15:49 UTC, merged