Modifications for GHE
urbanopt/geojson-modelica-translator pull request #526
Opened 2023-02-11 00:33 UTC by tanushree04

#### Any background context you want to provide?
#### What does this PR accomplish?
#### How should this be manually tested?
#### What are the relevant tickets?
#### Screenshots (if appropriate)

2023-02-13 21:25 UTC, vtnate commented
@tanushree04 Please run pre-commit (the two commands at: https://docs.urbanopt.net/geojson-modelica-translator/developer_resources.html#pre-commit) and try again.

2023-02-13 21:28 UTC, vtnate commented on tests/system_parameters/data/system_params_3.json
> +{
Please name this file to more easily describe its contents. Something like: `ghe_system_params.json`

2023-02-14 20:24 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
> +          }
@mitchute Please let me know if the GHE parameters in the schema looks okay

2023-02-14 21:35 UTC, vtnate requested changes
Can you group the ghe params together like `district_system`?

2023-02-14 21:35 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "The surface roughness of the pipe, in meters.",
Is this an industry standard term & unit? It's not intuitive to my uninformed eyes.

2023-02-14 21:35 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
> +          "$ref": "#/definitions/soil_def"
I feel like these schema items should be all inside a single field.

system_params_ghe.json:{ghe{{soil},{pipe},{borehole}

That's surely not the right notation, but think of it the way `district_system` is done in the sys-params.

2023-02-14 22:23 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "The surface roughness of the pipe, in meters.",
@vtnate which are you referring to?

2023-02-14 22:30 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          }
@ tanushree04 I don't see anything that jumps out as wrong here, though, we may be missing some parameters relating to the sizing. Take a look at the [demo files on the GHEDesigner repo](https://github.com/BETSRG/GHEDesigner/tree/main/demos), Specifically, the "rectangular" files. There may be a few others in there that need to be pulled in. Unfortunately, I haven't completed the documentation yet, so reach out if you have questions.

2023-02-14 22:56 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "The surface roughness of the pipe, in meters.",
Sorry. `Roughness` measured in meters sounds weird to me. I tried to admit that I don't know anything about it and this may just be my ignorance showing. 😄

2023-02-14 22:59 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "The surface roughness of the pipe, in meters.",
Yeah, it's a bit strange. Meters are the normal units, even if it is 1e-6 m.

2023-02-14 23:04 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          }
@tanushree04 FYI - notifying you again here. The @ reference above got broken somehow.

2023-02-16 19:56 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
> +          }
@mitchute thanks for pointing me to these files, I will pull these properties in. 
Is [this ](https://github.com/BETSRG/GHEDesigner/blob/main/demos/find_design_near_square_coaxial.json#L17) an outdated file? the pipe properties don't match with the documentation here https://github.com/BETSRG/GHEDesigner/blob/main/docs/cli.rst.

2023-02-16 23:44 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          }
@tanushree04 no, the file is current. This is for a coaxial-type borehole which we will not enable in our work. Stick with the single u-tube files, such as [this one](https://github.com/BETSRG/GHEDesigner/blob/main/demos/find_design_rectangular_single_u_tube.json).

2023-02-20 15:33 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
> +          "$ref": "#/definitions/soil_def"
@tanushree04 Can we have a larger item that encloses all these parameters? I think the root object should be `ground_heat_exchanger` and it should contain `soil`, `pipe`, and `borehole`. Does that make sense?

2023-02-23 18:17 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
> +          "$ref": "#/definitions/soil_def"
@vtnate I'm not sure you saw you've commented about this before - but this definitely makes sense thank you!

2023-02-23 20:16 UTC, tanushree04 commented
@mitchute This is ready for review

2023-03-01 17:42 UTC, tanushree04 commented
> @mitchute This is ready for review

The main thing to add to this would be descriptions for some of the parameters

2023-03-01 17:42 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
> +          "enum": [
@mitchute are there any other enums?

2023-03-01 17:43 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
> +          "hybrid"
@mitchute are there any other enums?

2023-03-01 17:43 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
> +          "nearsquare"
@mitchute are there any other enums?

2023-03-01 17:44 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
> +        "ghe_parameters": {
@mitchute from the properties listed below, are any required properties?

2023-03-01 17:54 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +        "ghe_parameters": {
As opposed to "default" properties? Can we default values here, or do users need to input every single thing? They all are required to do sizing, but we could possibly decide on some default values for some of them.

2023-03-01 17:57 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          "nearsquare"
Add `Rectangular`, too. There may be others later.

2023-03-01 19:06 UTC, mitchute reviewed
Thanks, @tanushree04. This looks really close aside from a few comments.

2023-03-01 19:06 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +        "description": "",
Flow type for ground heat exchanger sizing, in kg/s.

Enum could be either 'borehole' or 'system'.

2023-03-01 19:06 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +        "description": "",
Maximum heat pump entering fluid temperature used for ground heat exchanger sizing, in Celsius.

2023-03-01 19:06 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +        "description": "",
Minimum heat pump entering fluid temperature used for ground heat exchanger sizing, in Celsius.

2023-03-01 19:06 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +      "description": "",
Heat rejection or extraction loads of the ground heat exchanger used for ground heat exchanger sizing, in Watts. Heat extraction loads are positive, and heat rejection loads are negative.

2023-03-01 20:12 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +        "description": "",
Scratch that, I just double-checked and this is in lps.

2023-03-09 19:34 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
> +        "description": "",
@mitchute is there a description for `method` ?

2023-03-09 19:46 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
> +    "design_def": {
@mitchute what is the `description` field for `design_def`?

2023-03-09 21:09 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +    "design_def": {
Hmm, "Design parameters used for GHE sizing."

2023-03-09 21:09 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +        "description": "",
"GHE sizing method"

2023-03-14 19:45 UTC, tanushree04 commented
@mitchute this should have the descriptions and defaults added, and should be ready to be merged in

2023-03-14 20:55 UTC, vtnate commented
@tanushree04 please use pre-commit to make CI happy

2023-03-14 20:56 UTC, tanushree04 commented
> @tanushree04 please use pre-commit to make CI happy

@vtnate I did run the pre-commit commands..

2023-03-14 21:00 UTC, vtnate commented
> > @tanushree04 please use pre-commit to make CI happy
> 
> @vtnate I did run the pre-commit commands..

❤️  Thank you! Maybe there's something wrong with the pre-commit command being run on CI, that it's not seeing the changes recommended by the pre-commit you ran locally. I'm re-running and will dig in further. Thanks for the review request!

2023-03-14 21:02 UTC, tanushree04 commented
> > > @tanushree04 please use pre-commit to make CI happy
> > 
> > 
> > @vtnate I did run the pre-commit commands..
> 
> ❤️ Thank you! Maybe there's something wrong with the pre-commit command being run on CI, that it's not seeing the changes recommended by the pre-commit you ran locally. I'm re-running and will dig in further. Thanks for the review request!

Perfect, thank you!

2023-03-14 21:27 UTC, vtnate requested changes
I ran pre-commit and it made a bunch of changes to your test sys-param files. Did you run `poetry run pre-commit run --all-files`? That's the command I used.

2023-03-14 21:27 UTC, vtnate commented on tests/system_parameters/test_system_parameters.py
> +    def test_load_system_parameters_ghe(self):
Test names need to be unique. This is identical to the one above.

2023-03-21 04:20 UTC, mitchute requested changes
@tanushree04 thanks for all of your work on this! I made the last-minute change to the input schema on GHEDesigner to use diameters, so this should probably reflect that. Hopefully, this is a quick change. I think this is good after that.

2023-03-21 04:20 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "The radius of the inner pipe surface, in meters.",
Change to diameter

2023-03-21 04:20 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "The radius of the outer pipe surface, in meters.",
Diameter

2023-03-21 04:20 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "The radius of the borehole, in meters.",
Diameter

2023-03-21 04:20 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +      }
This isn't required anymore. We can remove this.

2023-03-22 20:30 UTC, tanushree04 commented
> @tanushree04 thanks for all of your work on this! I made the last-minute change to the input schema on GHEDesigner to use diameters, so this should probably reflect that. Hopefully, this is a quick change. I think this is good after that.

@mitchute sounds good, those changes should be added now

2023-03-22 20:48 UTC, mitchute commented on geojson_modelica_translator/system_parameters/schema.json
> +          "default": 0.19
There's a typo here I didn't catch earlier. Should be 0.15 m (should have been 0.075 before this change).

2023-03-22 20:50 UTC, mitchute approved these changes

2023-03-23 18:49 UTC, merged