Issue511 fixes
urbanopt/geojson-modelica-translator pull request #550
Opened 2023-05-17 15:59 UTC by JingWang-CUB

#### Any background context you want to provide?
URBANopt GHP project

#### What does this PR accomplish?
Fix GHE test breaks after system parameter file schema changes

#### How should this be manually tested?
poetry run pytest -m 'not compilation and not simulation' tests/model_connectors/test_borefield.py

#### What are the relevant tickets?
#511 

#### Screenshots (if appropriate)

2023-05-18 18:50 UTC, vtnate requested changes
Looks like `tests/model_connectors/test_borefield.py::DistrictSystemTest::test_build_district_system` is still looking for `tests/model_connectors/data/system_params_ghe_2.json` to use in the test, but it was deleted in this PR. Probably just need to change the test to point at the correct file.

2023-05-18 19:04 UTC, JingWang-CUB commented
@vtnate , right, I'm working on a few other changes including modifying the test to point to the correct file.

2023-05-24 22:10 UTC, vtnate commented
@JingWang-CUB This is not urgent. Sometime before you merge this, can you change the name to describe what is happening in the PR? Let's start with an action verb too (like `Fixing GHE tests` or `Adding functionality to GHE` or `Removing redundant GHE test files`).

2023-05-24 22:33 UTC, JingWang-CUB commented
@vtnate , the PR is ready for your review. The test now can pass and the model can simulate. I also included two temporary changes to suppress the known errors as we took out central heating plant parameters from the GHE system parameters file. Let me know if you have a better way to address those. Thanks!

2023-05-24 23:04 UTC, vtnate requested changes
Couple things still to change, but this is looking good. Thanks Jing!

2023-05-24 23:04 UTC, vtnate commented on tests/model_connectors/data/system_params_ghe.json
> +        "ghe_dir": "D:/GitHub/geojson-modelica-translator/tests/model_connectors/data",
CI can't find this file. Looks like it's an absolute path to somewhere on your computer, and when CI runs it isn't looking on your computer.

2023-05-24 23:04 UTC, vtnate commented on geojson_modelica_translator/model_connectors/networks/templates/NetworkAmbientWaterStub_Instance.mopt
> +    T={{ sys_params.district_system.fifth_generation.ghe_parameters.soil.undisturbed_temp}}+273.15,
We need to change the original 5G test sys-param file to include `ghe_parameters` instead of `central_heating_plant_parameters` now that you've made this change.

2023-05-25 14:30 UTC, JingWang-CUB commented on tests/model_connectors/data/system_params_ghe.json
> +        "ghe_dir": "D:/GitHub/geojson-modelica-translator/tests/model_connectors/data",
Correct. How should I fix this?

2023-05-25 15:43 UTC, vtnate commented on tests/model_connectors/data/system_params_ghe.json
> +        "ghe_dir": "D:/GitHub/geojson-modelica-translator/tests/model_connectors/data",
Make sure the code can handle both relative and absolute paths, and then put a relative path to the test_ghe_dir in this test sys-param file. Thanks!

2023-05-25 15:43 UTC, vtnate commented on geojson_modelica_translator/model_connectors/networks/templates/NetworkAmbientWaterStub_Instance.mopt
> +    T={{ sys_params.district_system.fifth_generation.ghe_parameters.soil.undisturbed_temp}}+273.15,
Since we're changing the instance template that the test file uses (and it breaks the test), I think we should change the test file as well.

2023-05-30 17:43 UTC, vtnate commented
@JingWang-CUB Try running pre-commit locally, and commit whatever changes it makes. That should make a bunch of these errors go away.

2023-05-31 20:51 UTC, vtnate commented on geojson_modelica_translator/model_connectors/networks/templates/NetworkAmbientWaterStub_Instance.mopt
> +    T={{ sys_params.district_system.fifth_generation.ghe_parameters.soil.undisturbed_temp}}+273.15,
As we discussed on the phone, this file needs an if/else to handle the ghe_parameters. Eventually we'll need to change the central_heating_parameters, because that doesn't make sense for a fifth-gen district, but that should be a separate PR from this.

2023-05-31 20:59 UTC, JingWang-CUB commented on geojson_modelica_translator/model_connectors/networks/templates/NetworkAmbientWaterStub_Instance.mopt
> +    T={{ sys_params.district_system.fifth_generation.ghe_parameters.soil.undisturbed_temp}}+273.15,
Hi Nate, I just pushed some other commits which fix this by adding an if/else statement. All pre-commit tests have passed. Let's see what the CI tests say.

2023-05-31 21:15 UTC, vtnate commented on geojson_modelica_translator/model_connectors/networks/templates/NetworkAmbientWaterStub_Instance.mopt
> +    {% if sys_params.district_system['fifth_generation']['ghe_parameters'] %}
Jinja has a weak if-engine. I think if you reverse this it'll work. Like, `if not ...['ghe_parameters']` then the normal way, else read the ghe_parameters.

2023-05-31 22:15 UTC, vtnate approved these changes

2023-06-01 17:10 UTC, merged