GHE Parameters: Remove loads as a required property
urbanopt/geojson-modelica-translator pull request #551
Opened 2023-05-17 21:32 UTC by tanushree04

#### Any background context you want to provide?
#### What does this PR accomplish?
#### How should this be manually tested?
#### What are the relevant tickets?
#### Screenshots (if appropriate)

2023-05-18 20:37 UTC, tanushree04 commented
@mitchute Should the ground loads be an array with associated GHE Feature ID - for cases there are more than 1 GHE in the network? 

https://github.com/urbanopt/geojson-modelica-translator/blob/0a5343e57a9dc9d9e45d6cd7eac99f81a5b501ed/tests/system_parameters/data/system_params_ghe.json#L101

https://github.com/BETSRG/GHEDesigner/blob/ff73e8a93cb3c1a564e1998d69fb6ebbe07a9766/ghedesigner/schemas/loads.schema.json#L4

2023-05-19 02:59 UTC, mitchute commented
@tanushree04 where are the unique number of boreholes and depths for each GHE going to go? Should those also be arrays, or do you think we need a separate object that holds the loads, NBH, and depth for each GHE instance?

2023-05-23 18:55 UTC, mitchute commented
> Are the depth of the borehole also unique for each GHE ?

Yes, that's correct.

2023-05-24 22:11 UTC, vtnate commented
@tanushree04 This is not urgent. Sometime before you merge this, can you change the name to describe what is happening in the PR? Let's start with an action verb too (like `Fixing GHE tests` or `Adding functionality to GHE` or `Removing redundant GHE test files`).

2023-05-30 23:10 UTC, vtnate requested changes
In general this is good. Gotta make the test file meet the schema definition, then we're good.

2023-05-30 23:10 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
Something in the test file under `ghe_parameters` doesn't meet the schema definition, which is causing the CI failures.

2023-05-30 23:40 UTC, tanushree04 commented on geojson_modelica_translator/system_parameters/schema.json
I updated the model_connectors examples as well - now we see a  KeyError: 'central_heating_plant_parameters' that needs to be probably fixed in Jing's PR

2023-05-31 13:56 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
Excellent. Yes, that KeyError is being addressed in Jing's PR

2023-05-31 20:41 UTC, vtnate approved these changes

2023-06-01 19:41 UTC, mitchute approved these changes

2023-06-05 20:26 UTC, merged