Closed-loop changes to existing test_single_ghe test
urbanopt/geojson-modelica-translator pull request #597
Opened 2023-11-06 22:17 UTC by JingWang-CUB

#### Any background context you want to provide?
URBANopt GHP project

#### What does this PR accomplish?
Change existing single GHE test to be closed-loop, which will overwrite the existing open-loop test

#### How should this be manually tested?
poetry run the test_single_ghe.py and then simulate the model in Dymola/OM

#### What are the relevant tickets?
None

#### Screenshots (if appropriate)

2023-11-06 22:18 UTC, JingWang-CUB commented
This is a PR for the closed-loop changes but it's not ready for review yet. I will be actively working on this.

2023-11-28 20:08 UTC, JingWang-CUB commented
CI is failing at modelica-formatter while it's passing on my computer. Any idea what's going on here? @vtnate 
Other than that, this PR is ready for your review.

2023-11-28 22:28 UTC, vtnate commented
I'll check out the modelica-formatter issues, and will review as soon as this is green. Thanks!

2023-11-28 23:19 UTC, vtnate requested changes
@JingWang-CUB Several changes in here that I am thrilled to see. Some are going to be necessary for MBLv10 too, so it's great to get them going now. Just the one question/concern on a variable name, otherwise this looks great.

2023-11-28 23:29 UTC, JingWang-CUB commented on geojson_modelica_translator/model_connectors/plants/templates/GroundTemperatureResponse.mo
> +  Boolean writegFun
This is for indication of whether the gfunction has been successfully written into a mat file. I copied it from somewhere else in MBL. I don't think this follows the traditional MBL naming convention. What would you like to change it to? I have no preference.

2023-11-28 23:33 UTC, vtnate commented on geojson_modelica_translator/model_connectors/plants/templates/GroundTemperatureResponse.mo
> +  Boolean writegFun
Let's follow the MBL instead of some other convention. 👍

2023-11-28 23:36 UTC, vtnate approved these changes
💥

2023-11-29 17:29 UTC, merged