Use Ubuntu 20 and fix CHP model
urbanopt/geojson-modelica-translator pull request #611
Opened 2024-01-10 20:30 UTC by vtnate

#### Any background context you want to provide?
- Our GMT_lib tests were failing in the new MBLv10 world. It turns out there is something in Ubuntu 22 that doesn't work with [this MBL model](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Experimental/DHC/Examples/Combined/SeriesConstantFlow.mo) that works fine in Ubuntu 20. Downgrading an Ubuntu version means maintaining more of the OM Docker installation code ourselves 👎.
- Fix & re-enable the CHP model that has been skipped for a while

#### What does this PR accomplish?
- Duplicates most of the OM dockerfile so we can set our own Ubuntu version
- Use the new Docker image in modelica_runner.py
- Re-enables the tests that were skipped because of this bug
- Update the Dockerfile version in the readme
- Bump to version 0.6.0 for the GMT

#### How should this be manually tested?
CI is sufficient, once a new Docker image (tagged `v2.0.1`) is pushed to dockerhub

2024-01-10 20:31 UTC, vtnate commented on tests/model_connectors/test_chp_system.py
> +            stop_time=9999,  # For 2.78 hours (in seconds)
Jiazhen is investigating initial values to determine why this simulation fails if it runs for more than 10,000 seconds

2024-01-11 14:56 UTC, nllong requested changes
nice, looking good.

The arm instance doesn't seem to build. Is this expected?

```
 => ERROR [linux/arm/v7 3/5] RUN export DEBIAN_FRONTEND="noninteractive" && echo "VERSION: 1.22.1" &&  306.0s
 => CANCELED [linux/amd64 3/5] RUN export DEBIAN_FRONTEND="noninteractive" && echo "VERSION: 1.22.1"   230.5s
 => CANCELED [linux/arm64 3/5] RUN export DEBIAN_FRONTEND="noninteractive" && echo "VERSION: 1.22.1"   220.1s
```

2024-01-11 14:56 UTC, nllong commented on geojson_modelica_translator/modelica/lib/runner/Dockerfile
> +RUN export DEBIAN_FRONTEND="noninteractive" && echo "VERSION: $VERSION" && test ! -z "$VERSION" && apt-get update && apt-get upgrade -qy && apt-get dist-upgrade -qy \
darg, regressing is painful... step back for now, but 10 steps forward in the near future

2024-01-11 14:56 UTC, nllong commented on tests/GMT_Lib/test_gmt_lib_des.py
>      @pytest.mark.simulation
sweet, so this works now?

2024-01-11 14:56 UTC, nllong commented on tests/model_connectors/test_chp_system.py
> +            stop_time=9999,  # For 2.78 hours (in seconds)
cool cool

2024-01-11 14:56 UTC, nllong commented on geojson_modelica_translator/model_connectors/plants/templates/HeatingPlantWithCHP.mot
> +  Boiler_TParallel_new boiHotWat(
not sure I like `_new` as an identifier, but I guess we needed something.

2024-01-11 15:01 UTC, vtnate commented on tests/GMT_Lib/test_gmt_lib_des.py
>      @pytest.mark.simulation
By using Ubuntu 20, yes!

2024-01-11 15:03 UTC, vtnate commented on geojson_modelica_translator/model_connectors/plants/templates/HeatingPlantWithCHP.mot
> +  Boiler_TParallel_new boiHotWat(
mmm, yeah, good point. I think Jiazhen made that model, so we can change it in a future PR.

2024-01-11 16:51 UTC, vtnate commented on geojson_modelica_translator/modelica/lib/runner/Dockerfile
> +    && apt-key add openmodelica.asc \
👍

2024-01-11 18:20 UTC, nllong approved these changes
most splendid

2024-01-11 18:20 UTC, merged