Force a dummy value for SHW in modelica loads even if not present
urbanopt/geojson-modelica-translator pull request #626
Opened 2024-03-11 21:00 UTC by vtnate

#### Any background context you want to provide?
We are required to have a value in the Service Hot Water column of the loads timeseries, even if it isn't used. This changes the first value to be `1` in case it is `0`.

_The UO SDK populates this column as of v0.11.0. Load files generated before then may be missing this data._
#### What does this PR accomplish?
- Adds a utility method which checks the modelica timeseries file for SHW values. If they are all zero, set the first to be `1`, then save the file back out.
#### How should this be manually tested?
Generate a model using timeseries data that does not have the SHW column populated. The updated file is `modelica_project/Loads/Resources/Data/<buildingname>/<load_timeseries>.mos`

2024-03-18 13:44 UTC, nllong requested changes
I wish we chatted... I wrote a helper method to do this in the 5G stuff. The method is ultimately in Modelica Builder.

https://github.com/urbanopt/geojson-modelica-translator/blob/develop/geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX_variable.py#L67-L77

```
mos_file = ModelicaMOS(save_filename)
            total_heating_load += mos_file.retrieve_header_variable_value('Peak space heating load', cast_type=float)
            total_cooling_load += mos_file.retrieve_header_variable_value('Peak space cooling load', cast_type=float)
            peak_water = mos_file.retrieve_header_variable_value('Peak water heating load', cast_type=float)
            total_swh_load += peak_water
            if peak_water == 0:
                peak_heat = mos_file.retrieve_header_variable_value('Peak space heating load', cast_type=float)
                peak_swh = max(peak_heat / 10, 5000)

                mos_file.replace_header_variable_value('Peak water heating load', peak_swh)
                mos_file.save()
```

2024-03-18 13:44 UTC, nllong commented on geojson_modelica_translator/utils.py
> +logging.basicConfig(
if we are going to specify the format, then we should propagate to all the other files, or setup in a config file.

2024-03-18 21:25 UTC, vtnate commented
@nllong You mean... have the modelica package do the modelica editing, and keep log messages consistent?

![image](https://github.com/urbanopt/geojson-modelica-translator/assets/19916206/4bd92dd8-d606-4a02-8434-f04ea38180de)

2024-03-19 02:26 UTC, nllong commented
> @nllong You mean... have the modelica package do the modelica editing, and keep log messages consistent?
> 
> ![image](https://private-user-images.githubusercontent.com/19916206/313840401-4bd92dd8-d606-4a02-8434-f04ea38180de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTU1MDEsIm5iZiI6MTcxMDgxNTIwMSwicGF0aCI6Ii8xOTkxNjIwNi8zMTM4NDA0MDEtNGJkOTJkZDgtZDYwNi00YTAyLTg0MzQtZjA0ZWEzODE4MGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAyMjY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNWFlZDgyODY1OTI3Y2MxNjE1MGE2MjhjNWIxMDI5YjFhNjEyYTMwZTM2MTIxZGU4NmFlOWE5NWUzYmFkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xJ4Q_2_nrfJBCFs6Q1JmrogCWuh2UQnIF481rZoY53Y)

I know, it's complicated. haha

2024-04-05 19:03 UTC, nllong approved these changes
thanks for using Modelica Builder! love it.

2024-04-05 19:03 UTC, merged