Add horizontal pipe properties
urbanopt/geojson-modelica-translator pull request #632
Opened 2024-04-19 18:53 UTC by tanushree04

#### Any background context you want to provide?
#### What does this PR accomplish?
#### How should this be manually tested?
#### What are the relevant tickets?
#### Screenshots (if appropriate)

2024-04-22 20:33 UTC, JingWang-CUB requested changes
Hi @tanushree04 , I left some comments. Otherwise, everything looks good. Should we also update how the default values are propagated, etc.?

2024-04-22 20:33 UTC, JingWang-CUB commented on geojson_modelica_translator/system_parameters/schema.json
> +              "$ref": "#/definitions/horizontal_piping_parameters_def"
The horizontal piping parameters should be added under "fifth_generation_def" following "central_pump_parameters".

2024-04-22 20:33 UTC, JingWang-CUB commented on geojson_modelica_translator/system_parameters/schema.json
> +              "type": "number"
@mitchute , should diameter ratio be limited to type "integer"?

2024-04-25 21:13 UTC, vtnate commented on geojson_modelica_translator/system_parameters/schema.json
> +              "$ref": "#/definitions/horizontal_piping_parameters_def"
@JingWang-CUB Am I correct that this means the horizontal piping work you're doing only applies to 5G systems? Do 4G (and earlier) systems have pipes that these parameters won't apply to?

2024-04-25 21:28 UTC, JingWang-CUB commented on geojson_modelica_translator/system_parameters/schema.json
> +              "$ref": "#/definitions/horizontal_piping_parameters_def"
Because 4G systems will likely have separate heating and cooling pipes so these parameters are not good fits for 4G.

2024-05-08 18:06 UTC, tanushree04 commented
@JingWang-CUB if we have an example file with horizontal piping parameters we can add those to the tests to test the schema change otherwise this should be wrapped up.

2024-05-08 19:06 UTC, JingWang-CUB commented
> @JingWang-CUB if we have an example file with horizontal piping parameters we can add those to the tests to test the schema change otherwise this should be wrapped up.

I have one example file [here](https://github.com/urbanopt/geojson-modelica-translator/pull/627/files#diff-62c760248f29ea0f70c769c71a193c6af73b7d53d657f50b32bf928a691c0c97) on my branch which can be used for testing the schema.

2024-06-25 20:55 UTC, merged