Adds method to process modelica results
urbanopt/geojson-modelica-translator pull request #646
Opened 2024-07-31 00:28 UTC by tanushree04

#### Any background context you want to provide?
#### What does this PR accomplish?
#### How should this be manually tested?
#### What are the relevant tickets?
#### Screenshots (if appropriate)

2024-08-08 16:57 UTC, vtnate requested changes
Please run pre-commit and address the linting & formatting changes.

Overall it's not clear to me what this command is for. Will you add more context to the PR description (and perhaps a bit to the cli command description) explaining what the output is, why someone would use this command, and how to interpret it?

2024-08-08 16:57 UTC, vtnate commented on geojson_modelica_translator/results_ghp.py
> +        # Collect key-value pairs directly
I love the amount of comments you have put into this file, thank you! Some of the comments feel unnecessary (the code is self-explanatory), and others feel insufficient. For instance, this one. I can see you are parsing the dict, so telling me that in a comment isn't very helpful. What would be more helpful is _why_ you're doing so. What will doing this allow you to accomplish?

2024-08-08 16:57 UTC, vtnate commented on management/uo_des.py
> +    default=15638400,
Why are you changing the defaults here? Did you mean to just pass these arguments to your call?

2024-08-08 16:57 UTC, vtnate commented on management/uo_des.py
> +    SYS_PARAM_FILE: Path/name to sys-param file, possibly created with this CLI.
This cli command doesn't take a sys-param file. Why add this?

2024-08-08 16:57 UTC, vtnate commented on management/uo_des.py
> -    :param number_of_intervals (int): number of intervals to run the simulation
These are valid inputs to the run-model command, aren't they? Why remove them?

2024-08-08 16:57 UTC, vtnate commented on management/uo_des.py
> +    # setup modelica results
This looks like it should be for your new command, lower down in this file.

2024-08-08 16:57 UTC, vtnate commented on management/uo_des.py
> +    \b
Add a space above the `\b` for it to format as expected when you use it for real.

2024-08-08 16:57 UTC, vtnate commented on management/uo_des.py
> +    result.calculate_results()
This takes an incredibly long time to run on my machine (hours so far and it's not done). Is that expected?

2024-08-08 16:57 UTC, vtnate commented on tests/geojson_modelica_translator/test_results_ghp.py
> +        assert csv_file_path.exists(), f"File does not exist at path: {csv_file_path}"
This generates a file as expected. I don't know if the contents are appropriate or not. Can you make some additional assertions so we'll know if the file has been populated correctly?

2024-08-13 17:05 UTC, tanushree04 commented
https://github.com/urbanopt/geojson-modelica-translator/issues/645


This needs to be incorporated

2024-08-13 19:16 UTC, vtnate commented
> #645
> 
> This needs to be incorporated

Ah. That is in #644.

2024-08-26 23:40 UTC, tanushree04 commented
> pre-co

what is the pre commit command?

2024-08-27 13:49 UTC, vtnate commented
> what is the pre commit command?

`poetry run pre-commit run -a`

2024-08-27 13:53 UTC, vtnate commented on management/uo_des.py
> +    default=15638400,
If we want to change the default timestep for all users, we can do that. That would be in `--step-size`, which was previously at 90 seconds before your change to 1 hour.

To change to running for a full year we'd change the start-time to 0 and the end time to whatever it is in seconds.

2024-09-18 19:56 UTC, tanushree04 commented on management/uo_des.py
> +    result.calculate_results()
yes

2024-09-18 19:56 UTC, tanushree04 commented on tests/geojson_modelica_translator/test_results_ghp.py
> +        assert csv_file_path.exists(), f"File does not exist at path: {csv_file_path}"
added

2024-09-18 19:57 UTC, tanushree04 commented on management/uo_des.py
> -    :param number_of_intervals (int): number of intervals to run the simulation
corrected this

2024-09-23 23:32 UTC, tanushree04 commented on management/uo_des.py
> +    default=15638400,
updated to 1 yr simulation with 15 min intervals

2024-09-30 20:04 UTC, tanushree04 commented on tests/geojson_modelica_translator/test_results_ghp.py
> +        csv_file_path = (
since we are already testing the run command it is sufficient to test the process command separately. I have also added a light weight model to this test.

2024-10-01 17:56 UTC, vtnate approved these changes
Making use of results! ❤️ This is fantastic. In FY25 we should incorporate some of Nicholas' work from the UO_DES repo to expand this even more.

2024-10-01 18:45 UTC, merged