Simplify sys params to closer match reality
urbanopt/geojson-modelica-translator pull request #659
Opened 2024-09-18 16:41 UTC by vtnate

#### Any background context you want to provide?
We developed the schema to cover many potential parameters. This cleans up a few of them, to reduce duplication and have parameters where they make sense.
#### What does this PR accomplish?
- Move `pump_design_head` & `pump_flow_rate` to district params instead of individual ETS params.
#### How should this be manually tested?
CI is technically efficient. Manual review to determine if this is the appropriate place for them to be.
#### What are the relevant tickets?
Resolves #629 
#### TODO
- Clean up schema, so we can include required parameters of 4th gen & 5th gen districts

2024-09-23 17:03 UTC, JingWang-CUB requested changes
Hi @vtnate , please see the detailed review comments. Otherwise, it looks good!

2024-09-23 17:03 UTC, JingWang-CUB commented on tests/data_shared/system_params_des_5g.json
> +        "pump_flow_rate": 0.01
ThermalNetwork should be aware of these changes for its sizing of GHEs.

2024-09-23 17:03 UTC, JingWang-CUB commented on geojson_modelica_translator/system_parameters/time_series_template.json
> +        "pump_flow_rate": 0.01
In other words, these should be 5G only changes.

2024-09-23 17:05 UTC, vtnate commented on tests/data_shared/system_params_des_5g.json
> +        "pump_flow_rate": 0.01
I have an open PR on TN doing just that: https://github.com/NREL/ThermalNetwork/pull/37.

2024-09-23 17:08 UTC, vtnate commented on geojson_modelica_translator/system_parameters/time_series_template.json
> +        "pump_flow_rate": 0.01
Should the entire `central_pump_parameters` block be removed from 4G districts?

We still want to remove the head & flow-rate from all ETS parameters, correct (as I did in this PR)?

2024-09-23 17:16 UTC, JingWang-CUB commented on geojson_modelica_translator/system_parameters/time_series_template.json
> +        "pump_flow_rate": 0.01
To your first question, yes. Can you provide an example of your second question?

2024-09-23 17:25 UTC, JingWang-CUB commented on geojson_modelica_translator/system_parameters/time_series_template.json
> +        "pump_flow_rate": 0.01
Yes, deleting the `pump_flow_rate` and `pump_design_head` from the 5g ETS parameters is appropriate.

2024-09-23 20:07 UTC, JingWang-CUB approved these changes

2024-09-27 20:35 UTC, nllong approved these changes
we are probably need to start versioning this file soon... 

changes look swell.

2024-09-27 20:35 UTC, nllong commented on geojson_modelica_translator/system_parameters/schema.json
> +          "description": "The GeoJSON ID as defined in the GeoJSON file.",
nice cleanup

2024-10-01 18:57 UTC, merged