Fall 2024 documentation updates
urbanopt/geojson-modelica-translator pull request #664
Opened 2024-10-08 20:35 UTC by vtnate

#### Any background context you want to provide?
Trying to keep docs up to date with the current state of the package
#### What does this PR accomplish?
Minor docs changes as time goes by
#### How should this be manually tested?
- Manually read & compare to [existing site](https://docs.urbanopt.net/geojson-modelica-translator/index.html)
- [Getting started](https://docs.urbanopt.net/geojson-modelica-translator/getting_started.html) page
#### What are the relevant tickets?
#### Screenshots (if appropriate)

2024-12-12 17:26 UTC, vtnate commented on .github/workflows/documentation_site.yml
> +      - docs/**
This workflow only kicks off if a change is made to the `docs` folder on `main` - Do we want to update docs on push to `develop` as well?

2024-12-12 17:26 UTC, vtnate commented on docs/input_file_documentation.md
> +The system parameter properties can be found in the `Schema` section of this documenation
Is it reasonable to just say "go look over there"? I briefly tried to link to that page, but since it's not a regular *.md file I stopped before getting too crazy.

2024-12-12 17:26 UTC, vtnate commented on geojson_modelica_translator/system_parameters/system_parameter_properties.json
I changed the name of the sys-param schema file. Is that kosher?

2024-12-16 21:29 UTC, nllong commented on .github/workflows/documentation_site.yml
> +      - docs/**
no, it should only be on main.

2024-12-16 23:00 UTC, nllong commented
WOW! This is nice lookiiinnngg!

<img width="1091" alt="image" src="https://github.com/user-attachments/assets/0d9b7fbf-988a-4fff-988f-6f1931a39922" />

2024-12-16 23:00 UTC, nllong commented on geojson_modelica_translator/system_parameters/system_parameter_properties.json
I think so, as long as you updated the name in this repo everywhere. I doubt anyone is referencing the file outside of this project.

2024-12-16 23:07 UTC, nllong requested changes
Review and merge #682 

Can you make this a table so all the links are aligned?

<img width="592" alt="image" src="https://github.com/user-attachments/assets/a5d76e7d-cc69-4af4-8102-c42abd7ef462" />

2024-12-17 15:59 UTC, nllong approved these changes
let's gooo.. this is much cleaner than RST. Thanks for making the migration happen.

2024-12-17 18:15 UTC, merged